# CONFIG_GPIO=y
# CONFIG_LOG=y
# CONFIG_LED_STRIP=y
# CONFIG_LED_STRIP_LOG_LEVEL_DBG=y
CONFIG_SENSOR=y
# CONFIG_LOG_DEFAULT_LEVEL=4
# CONFIG_TEMP_NRF5=y
# Bluetooth configuration
CONFIG_BT=y
# CONFIG_BT_DEBUG_LOG=y
CONFIG_BT_MAX_CONN=5
CONFIG_BT_L2CAP_TX_BUF_COUNT=5
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="GARAGE"
CONFIG_BT_DEVICE_APPEARANCE=962
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
# HC-SR04 Ultrasonic sensor
CONFIG_HC_SR04=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
# CONFIG_NVS_LOG_LEVEL_DBG=y   # optional for debugging
# CONFIG_NRFX_TIMER=y
CONFIG_NRFX_PWM=y
# CONFIG_NRFX_PWM1=y
# CONFIG_NRFX_PWM_LOG=y